### ISSUE TITLE
Skeleton App

### ISSUE THREAD

**Issue by benceruleanlu** [benceruleanlu/reefscape-app#6]
We've decided to build a skeleton app just to establish a connection to the server and make sure that we can connect to the **right** server.

This will require the creation of another GitHub repository for the server, which will be done by @benceruleanlu and he will add both Dalton and Owen to the repository.

**Comment by benceruleanlu** [comment]
Created the repo and added Dalton. Will ignore Owen for now, it seems he prefers being in the Controls subteam.

**Comment by XiongDa457** [comment]
We split this ticket in to two smaller tickets
#7
